### ISSUE TITLE
[REQUEST] To-do

### ISSUE THREAD

**Issue by Lukas-Batema** [Lukas-Batema/pyslots#7]
- [x] Add more variations of the slot game
- [x] Add a Variation menu
- [ ] Add a DB to store User games and "money" values
- [x] Add user inputted amount to gamble
- [x] ~~Potentially add more than just slots :)~~
